[tool.poetry]
name = "protol"
version = "0.1.0"
description = ""
authors = ["adriyansyahmf <adriyansyahmf0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
attrs = "^22.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
